apiVersion: v1
data:
  X-Different-Name: "true"
  X-Request-Start: t=${msec}
  X-Using-Nginx-Controller: "true"
  nikhil-request-header: "request data"
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: ingress-nginx